//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavİlan
    {
        public int SinavIlanNo { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<int> DersId { get; set; }
        public Nullable<int> sinifId { get; set; }
        public Nullable<int> saatId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public Nullable<int> salonId { get; set; }
        public Nullable<int> bolumID { get; set; }
        public string aciklama { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Kullanicis Kullanicis { get; set; }
        public virtual Saats Saats { get; set; }
        public virtual Salons Salons { get; set; }
        public virtual Sinifs Sinifs { get; set; }
    }
}
